### ISSUE TITLE
Find a better way to start the rabbit listener and webhook

### ISSUE THREAD

**Issue by dcermak** [openSUSE/scm-staging#26]
Currently the RabbitMQ listener (`rabbit_listener`) and the webhook (the tornado application itself) "talk" to each other via a sqlite database. But both are started separately in the same container which makes automated restarts rather inconvenient. It would be good if both could be part of the same process or separate containers (although that's rather wasteful)?

**Comment by brunoleon** [comment]
May be the way to go is 3 containers:
- sqlite
- rabbitMQlistener
- tornado

the two last ones having a shared volume which is sqlite

**Comment by dcermak** [comment]
> May be the way to go is 3 containers:
> - sqlite

sqlite is just the database file, putting that file into a separate
container is rather pointless

> - rabbitMQlistener
> - tornado
>
> the two last ones having a shared volume which is sqlite

Yes, that would be an option. It feels a bit wasteful, as we'll
duplicate the whole image, but maybe we can avoid that somehow by just
swapping out CMD?

**Comment by dcermak** [comment]
First step: https://github.com/openSUSE/scm-staging/pull/28

**Comment by AvengerMoJo** [comment]
> First step: #28
As #28 is closed, services could be started by webhook or poetry run app. We do need to make updates to the dockerfile for the container. Do, we may need to prepare a systemd script for rpm installation?

**Comment by dcermak** [comment]
AvengerMoJo ***@***.***> writes:

>> First step: #28
> As #28 is closed, services could be started by webhook or poetry run app. We do need to make updates to the dockerfile for the container. Do, we may need to prepare a systemd script for rpm installation?

The actual work was done by you in
https://github.com/openSUSE/scm-staging/pull/29

What should be done now:
- adjust the Dockerfile to only build one target
- provide a systemd service generated via `podman generate systemd`

I think we can defer the systemd script for rpm installation to
https://github.com/openSUSE/scm-staging/issues/14
