### ISSUE TITLE
SR accepted but PR not merged

### ISSUE THREAD

**Issue by VaiTon** [openSUSE/scm-staging#42]
- https://src.opensuse.org/pool/python-cloup/pulls/3
- https://build.opensuse.org/request/show/1099717

**Comment by dcermak** [comment]
Thanks for the report!

I'll take a look when I'm back from vacation (hopefully next week).

**Comment by dcermak** [comment]
> Also in this case https://src.opensuse.org/pool/python-cloup/pulls/4 it synced with rpm/ and not pool/

What makes you think that?

**Comment by dcermak** [comment]
> * https://src.opensuse.org/pool/python-cloup/pulls/3
> 
> * https://build.opensuse.org/request/show/1099717

I must confess that I have no idea what happened here yet. It appears as if the bot never got the message, that the SR got accepted.

I'll keep digging a bit and will add some cleanup code, that will merge your PR after the fact.

**Comment by VaiTon** [comment]
> > Also in this case https://src.opensuse.org/pool/python-cloup/pulls/4 it synced with rpm/ and not pool/
> 
> What makes you think that?

https://src.opensuse.org/rpm/python-cloup/commit/ff3e003483156f2df8a243e8baa076ec4762e8b9

**Comment by dcermak** [comment]
> > > Also in this case https://src.opensuse.org/pool/python-cloup/pulls/4 it synced with rpm/ and not pool/
> > 
> > 
> > What makes you think that?
> 
> https://src.opensuse.org/rpm/python-cloup/commit/ff3e003483156f2df8a243e8baa076ec4762e8b9

No, what you see there is the OBS->gitea sync script that is syncing into the rpm/ organization. It is unrelated to the bot.

**Comment by VaiTon** [comment]
Also this has the same issue i think? https://src.opensuse.org/pool/python-cloup/pulls/4

**Comment by dcermak** [comment]
> Also this has the same issue i think? https://src.opensuse.org/pool/python-cloup/pulls/4

Yes, it looks very much like that. Additionally, the cleanup code didn't run because it was unable to merge another PR before it in the queue and now pr 4 is no longer mergeable… I am afraid that the git repo will need manual fixing to get it in sync with Factory.

Should I take care of that?

**Comment by VaiTon** [comment]
> Should I take care of that?

I can create another PR to sync, but I guess it will need to get approved in OBS if I understand correctly

**Comment by dcermak** [comment]
> I can create another PR to sync, but I guess it will need to get approved in OBS if I understand correctly

Please create one that mirrors what is in Factory into https://src.opensuse.org/pool/python-cloup/, I'll merge it manually.

**Comment by VaiTon** [comment]
Hey @dcermak , any way of getting the repo back in sync with OBS?

**Comment by dcermak** [comment]
I have pushed to the factory branch to be in sync with openSUSE:Factory again. Can you please double check if the new state is how you'd like it?

**Comment by VaiTon** [comment]
Yup, thanks!
