### ISSUE TITLE
merge request declined by factory-auto due source_validator

### ISSUE THREAD

**Issue by ailiop-suse** [openSUSE/scm-staging#45]
My src.o.o git merge requests are getting declined by obs/factory-auto, source_validator is complaining that it doesn't recognize tar.xz (and thus it cannot validate the gpg signature of the pkg).

Example: https://build.opensuse.org/request/show/1117680#request-history

So 25-keyring-validate fails with "xzcat is failing (xzcat: xfsprogs/xfsprogs-6.5.0.tar.xz: File format not recognized).".

Running the source_validator locally doesn't produce any errors.

Checking out devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs locally and running source_validator doesn't produce any errors:

`osc co devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs && cd $_ && /usr/lib/obs/service/source_validator`

> gpg: Signature made Thu 12 Oct 2023 01:32:45 PM CEST
> gpg:                using EDDSA key FA406E206AFF7873897C6864B45618C36A24FD23
> gpg:                issuer "cem@kernel.org"
> gpg: Good signature from "Carlos Eduardo Maiolino <carlos@maiolino.me>" [unknown]
> gpg:                 aka "Carlos Eduardo Maiolino <cem@kernel.org>" [unknown]
> gpg:                 aka "Carlos Eduardo Maiolino <cmaiolino@redhat.com>" [unknown]

`bash -x /usr/lib/obs/service/source_validators/25-keyring-validate`

> + xzcat /home/ailiopoulos/devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs/devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs/xfsprogs-6.5.0.tar.xz
> + gpg --homedir /tmp/tmp.ByDL9cYDdz -q --no-default-keyring --keyring /tmp/tmp.ByDL9cYDdz/.gpg-keyring --trust-model always -q --verify -- /home/ailiopoulos/devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs/devel:Factory:git-workflow:staging:ailiopoulos:xfsprogs:3/xfsprogs/xfsprogs-6.5.0.tar.sign -

xzcat doesn't complain and is able to decompress the archive.

So this may be some issue with the factory-auto build environment?

**Comment by dirkmueller** [comment]
yes, we're missing `git-lfs` in the environment. Looking at getting that fixed..

**Comment by dirkmueller** [comment]
https://build.opensuse.org/request/show/1118614

**Comment by dirkmueller** [comment]
we've redeployed the new container. the new one broke other things but this one is fixed.
