### ISSUE TITLE
Improve scmsync rejection message of factory-auto

### ISSUE THREAD

**Issue by jengelh** [openSUSE/scm-staging#51]
https://build.opensuse.org/request/show/1189033

Observed decline message:

`Expected a devel project scm sync from https://src.opensuse.org/pool/bcachefs-tools`

Expected decline message:

`Submission declined because the origin is https://src.opensuse.org/ddiss/bcachefs-tools. The origin must be https://src.opensuse.org/pool/bcachefs-tools instead.`

**Comment by dirkmueller** [comment]
that's a bit long. but I agree with you it should be more verbose. 

forwarded as https://github.com/openSUSE/openSUSE-release-tools/pull/3128
